version: '2'
services:
    master:
      container_name: hadoop_master
      image: paultomchik/hadoop-cluster
      environment:
        - CLUSTER_ROLE=master
      hostname: master
      volumes:
        - ./data/master-data/:/data/
    slave1:
      container_name: hadoop_slave1
      image: paultomchik/hadoop-cluster
      hostname: slave1
      volumes:
        - ./data/slave1-data/:/data/
    slave2:
      container_name: hadoop_slave2
      image: paultomchik/hadoop-cluster
      hostname: slave2
      volumes:
        - ./data/slave2-data/:/data/
